image: php:latest

stages:
  - build
  - test

cache:
  paths:
  - vendor/

composer:
  stage: build
  script:
    - apt-get update
    - apt-get install --assume-yes git zip unzip
    - export APP_ENV=testing
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install

phpMess:
  stage: test
  script:
    - php vendor/bin/phpmd src/ text cleancode,controversial,codesize,design,naming,unusedcode
  allow_failure: true

phpUnit:
  stage: test
  script:
    - php vendor/bin/phpunit --colors

coverageTest:
  stage: test
  script:
    - php vendor/bin/phpunit --colors --debug --coverage-text
  allow_failure: true

codeSniffer:
  stage: test
  script:
    - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
    - php vendor/bin/phpcs --standard=PSR4 -w --colors src/
  allow_failure: true