image: php:latest

stages:
  - build
  - test

cache:
  paths:
  - vendor/

before_script:
  - apt-get update
  - apt-get install --assume-yes git zip unzip

composer:
  stage: build
  script:
    - export APP_ENV=testing
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install


phpUnit:
  stage: test
  script:
    - cat .env
    - php vendor/bin/phpunit --colors

coverageTest:
  stage: test
  script:
    - php vendor/bin/phpunit --colors --debug --coverage-text

codeSniffer:
  stage: test
  script:
    - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
    - php vendor/bin/phpcs --standard=PSR4 -w --colors app/

phpMess:
  stage: test
  script:
    - php vendor/bin/phpmd src/ text cleancode,controversial,codesize,design,naming,unusedcode