language: php

sudo: false

php:
  - 7.1
  - 7.2

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR


before_script:
  - mkdir -p build/logs
  - composer self-update || true
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - find src -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors detected" )
  - echo $TRAVIS_PULL_REQUEST
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then ./vendor/bin/phpunit --colors --configuration=phpunit-merge.xml; fi

after_success:
 - php vendor/bin/coveralls -v




